import type { Dish } from '../../types/domain'

export const INGREDIENT_EMOJI_MAP: Record<string, string> = {
  'drumstick': '🌿',
  'raw banana': '🍌',
  'yam': '🍠',
  'beans': '🫘',
  'carrot': '🥕',
  'raw mango': '🥭',
  'green beans': '🫘',
  'cabbage': '🥬',
  'pumpkin': '🎃',
  'cowpeas': '🫘',
  'ash gourd': '🥒',
  'coconut milk': '🥥',
  'bitter gourd': '🥗',
  'yogurt': '🫙',
  'toor dal': '🫘',
  'shallots': '🧅',
  'tomato': '🍅',
  'moong dal': '🫘',
  'coconut': '🥥',
  'pepper': '🌶️',
  'eggplant': '🍆',
  'potato': '🥔',
  'jaggery': '🍯',
  'bottle gourd': '🥬',
  'chana dal': '🫘',
  'green chili': '🌶️',
  'flat beans': '🫛',
}

export const DEFAULT_STAPLES = [
  'salt',
  'turmeric',
  'chili powder',
  'oil',
  'coconut oil',
  'curry leaves',
  'mustard seeds',
  'cumin seeds',
  'ginger',
  'garlic',
  'tamarind',
  'dried red chilies',
  'coconut (grated)',
  'ghee',
  'asafoetida',
]

export const DEFAULT_DISHES: Dish[] = [
  {
    id: 'avial',
    name: 'Avial',
    category: 'sabji',
    mainIngredients: ['drumstick', 'raw banana', 'yam', 'beans', 'carrot', 'raw mango'],
    emoji: '🥗',
    bgColor: '#d4edda',
    referenceText: 'Mixed vegetables in coconut and yogurt. Palakkad essential.',
  },
  {
    id: 'beans-thoran',
    name: 'Beans Thoran',
    category: 'sabji',
    mainIngredients: ['green beans'],
    emoji: '🫘',
    bgColor: '#d4edda',
    referenceText: 'Dry stir-fry with grated coconut and curry leaves.',
  },
  {
    id: 'cabbage-thoran',
    name: 'Cabbage Thoran',
    category: 'sabji',
    mainIngredients: ['cabbage'],
    emoji: '🥬',
    bgColor: '#d4edda',
    referenceText: 'Quick dry sabji, goes with rice and dal.',
  },
  {
    id: 'erissery',
    name: 'Erissery',
    category: 'sabji',
    mainIngredients: ['pumpkin', 'cowpeas'],
    emoji: '🎃',
    bgColor: '#fff3cd',
    referenceText: 'Pumpkin and cowpeas with roasted coconut. Classic Kerala.',
  },
  {
    id: 'olan',
    name: 'Olan',
    category: 'sabji',
    mainIngredients: ['ash gourd', 'cowpeas', 'coconut milk'],
    emoji: '🥒',
    bgColor: '#e8f5e9',
    referenceText: 'Subtle ash gourd and cowpeas in thin coconut milk.',
  },
  {
    id: 'mezhukkupuratti',
    name: 'Mezhukkupuratti',
    category: 'sabji',
    mainIngredients: ['raw banana', 'bitter gourd'],
    emoji: '🍌',
    bgColor: '#fff9c4',
    referenceText: 'Simple dry stir-fry with shallots and coconut oil.',
  },
  {
    id: 'kaalan',
    name: 'Kaalan',
    category: 'sabji',
    mainIngredients: ['raw banana', 'yam', 'yogurt'],
    emoji: '🫙',
    bgColor: '#fff3cd',
    referenceText: 'Raw banana and yam in thick coconut-curd gravy.',
  },
  {
    id: 'sambar',
    name: 'Sambar',
    category: 'curry',
    mainIngredients: ['toor dal', 'drumstick', 'shallots', 'tomato'],
    emoji: '🍲',
    bgColor: '#ffe0b2',
    referenceText: 'Daily staple. Palakkad sambar uses more shallots than tomato.',
  },
  {
    id: 'parippu-curry',
    name: 'Parippu Curry',
    category: 'curry',
    mainIngredients: ['moong dal', 'coconut'],
    emoji: '🫘',
    bgColor: '#fff9c4',
    referenceText: 'Simple moong dal with coconut paste and ghee tempering.',
  },
  {
    id: 'rasam',
    name: 'Rasam',
    category: 'curry',
    mainIngredients: ['tomato', 'pepper'],
    emoji: '🍵',
    bgColor: '#ffccbc',
    referenceText: 'Thin digestive broth with tomato, pepper and tamarind.',
  },
  {
    id: 'pulissery',
    name: 'Pulissery',
    category: 'curry',
    mainIngredients: ['raw mango', 'yogurt', 'coconut'],
    emoji: '🥭',
    bgColor: '#fff9c4',
    referenceText: 'Moru curry with raw mango. Goes with rice.',
  },
  {
    id: 'ringan-bateta',
    name: 'Ringan Bateta',
    category: 'gujarati',
    mainIngredients: ['eggplant', 'potato', 'tomato', 'jaggery'],
    emoji: '🍆',
    bgColor: '#e2d9f3',
    referenceText: 'Gujarati-style sweet-spicy brinjal and potato.',
  },
  {
    id: 'dudhi-chana',
    name: 'Dudhi Chana',
    category: 'gujarati',
    mainIngredients: ['bottle gourd', 'chana dal', 'tomato', 'jaggery'],
    emoji: '🥬',
    bgColor: '#d4edda',
    referenceText: 'Bottle gourd and split chickpea sabji, light and nutritious.',
  },
  {
    id: 'batata-shaak',
    name: 'Batata nu Shaak',
    category: 'gujarati',
    mainIngredients: ['potato', 'tomato', 'green chili'],
    emoji: '🥔',
    bgColor: '#fff9c4',
    referenceText: 'Dry everyday potato sabji, quick to make.',
  },
  {
    id: 'valor-papdi',
    name: 'Valor Papdi',
    category: 'gujarati',
    mainIngredients: ['flat beans', 'potato', 'jaggery'],
    emoji: '🫛',
    bgColor: '#d4edda',
    referenceText: 'Flat beans and potato in sweet-spicy Gujarati masala.',
  },
]
